### ISSUE TITLE
Autologout when key is expired

### ISSUE THREAD

**Issue by sidPhoenix17** [sidPhoenix17/COVID#146]
Currently only sticker comes when login token is expired.

**Comment by sidPhoenix17** [comment]
users get confused. rather better to just logout the user and make them login again.

**Comment by sidPhoenix17** [comment]
token_blacklist is empty in prod. Should I be concerned? @shailysangwan

**Comment by shailysangwan** [comment]
Can you check by logging in as a volunteer and then logging out? If there
still won't be any, something isn't working right.
